### ISSUE TITLE
[BUG]: Mobile Dashboard scrolling and responsiveness

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#119]
I have provided a video to showcase the weird behaviour on mobile. The main issue is that some of the components overflow the bottom of the page. This leads to the DashboardSidebar disappearing when scrolling down on the page, which shouldn't be the case. It should always stay locked to the screen size. 

## Tasks:
- [x] fix the components overflowing the bottom of the page
- [x] fix the DashboardSIdebar dissapearing when scrolling down
- [x] on the home page of the dashboard, the component that the TradingViewWIdget is in grows as you scroll down, and you are left with containers being pushed below the screen.
- [x] the background of the webpage is a lighter black and then a deep black, this is shown when minimizing the sidebar, and is the same color discrepancy wehn scrolling to the bottom of the page.

PLEASE CHECK DISCORD FOR A VIDEO under the #119 Thread.

Here are some pictures:

Scrollng below the page and dashboard header disappearing
![Image](https://github.com/user-attachments/assets/7a5a7b8f-d79c-4b81-bc1d-78e950100e28)

Background Coloration is off
![Image](https://github.com/user-attachments/assets/6d215bfd-6360-49df-9a6b-b4b68003ba84)

**Comment by jjfantini** [comment]
Closed with #123
