### ISSUE TITLE
[FEAT]: Create `PortfolioTable` component

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#27]
## Main Goal
- Maintain and manage selected assets for each user, allowing multiple watchlists and providing portfolio analytics. You will be creating a React component using tanstack-table/ag-grid (preferably ag-grid) that shows the selected users watchlist in the table. This table will get the data from `api/portfolio-data` route.  The user should be able to select which watchlist is displayed and  then that data will be fetched and displayed. The watchlist that is selected will have a list of tickers that the user has put in that watchlist. These tickers are to be passed to `api/portfolio-data` and the `PortfolioTable` will present the results.

### Tasks

1. **Create Portfolio Table**
   - [x] Create a table for portfolio management in the database.
     - Columns should include (will be returned from `portfolio-data`):
       - Ticker
       - Last close
       - Asset class
       - Sector
       - Mandelbrot Channel
       - Risk / Reward
       - Up/down ratio
       - humblSuggestion
    This data will be available form a function in `humblDATA` from the `api/portfolio-data` route and it will be returned as a JSON object.

2. **Implement Unique Portfolios Per User**
   - [x] Ensure the portfolio is unique to each user, and that they only have access to their watchlists, not other users.
   - [x] Allow users to have various tickers in their watchlists shown on the table.

3. **Set Up Preloaded Watchlists for Premium and Power Users**
   - [ ] Preload 1 watchlist for premium and 2 for power users.
   - [ ] Allow users to choose which watchlists to preload.

### Notes
- This task is linked to #28, please take a look to see what the portfolio should look like (basic)
