### ISSUE TITLE
[FEAT]: Add Payment Integration and Pricing page

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#29]
## Main Goal
- Add a pricing page to the `/(landing-page)` showcasing features for each subscription tier and integrating Stripe payment.

## Tasks

NextUI Pro components should be used.

1. **Create Pricing Page**
   - [x] Add a pricing page to the platform. Each subsription should have the ability to do monthly or annual billing, setup so that this is correctly billed on stripe
   - [x] Showcase features for each subscription tier (e.g., Premium, Power).
   - [x] Include subscription plans:
     - humblPEON: $0
     - humblPREMIUM: $12
     - humblPOWER: $35
     - humblPERMANENT: $999

2. **Integrate Stripe Payment**
   - [x] Integrate Stripe payment gateway into the pricing page for users to purchase and subscribe to the service.

3. **Add Comparison Pricing**
   - [x] Add comparison pricing below vs. competitors:
     - MFR
     - Longbow
     - Alphaticks
     - PortfolioLabs

## Notes
- The pricing page should clearly display the features and pricing for each subscription tier.
- Ensure the payment integration with Stripe is seamless and secure.
- The comparison section should highlight the advantages and competitive pricing of our platform compared to others in the market.

**Comment by jjfantini** [comment]
The Pricing Page should look like this:


https://www.nextui.pro/components/marketing/pricing-comparison#component-pricing-comparison-with-blurred-background

**Comment by jjfantini** [comment]
For the comparison of features to our competitors, I would like you to include a section on the pricing page, beautifully presented below the pricing of the various plans to include 

![Image](https://github.com/humblFINANCE/humblFINANCE-frontend/assets/63276164/58ec212f-a36c-48c1-99e4-5d211741f605)

**Comment by jjfantini** [comment]
Closed with #46
