### ISSUE TITLE
[FEAT]: UserDropdown in Dashboard Header

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#3]
## Main Goals

- Create a clickable `UserDropdown` with the following items:
  - Settings (route user to a Profile Settings Page)
  - ThemeSwitch (to change between dark & light mode), include moon and sun icons for respective settings
- Ensure Profile Settings DropdownItem fires the profile settings modal
- Ensure logout button fires the `LogoutModal.tsx`

## Tasks

- [x] **Create UserDropdown Component:**
  - Scaffold the `UserDropdown.tsx` to include:
    - Settings item (routes to Profile Settings Page)
    - ThemeSwitch with moon and sun icons for dark and light modes

- [x] **Integrate UserDropdown in Dashboard Header:**
  - Resolve issues with integrating `UserDropdown` (client component) into `DashboardSidebar` (server component)
  - Consider separating the Dashboard header from `DashboardSidebar.tsx` to avoid conflicts

- [x] **Profile Settings Page:**
  - Allow editing of the following user details:
    - Display name
    - Email
    - Password
    - Profile picture
    - Accent color
    - Default theme (dark or light)
    - Notification settings for trade alerts
    - OpenBB Personal Access Token (under "Financial Services" section)
    - InteractiveBroker API Key (under "Financial Services" section)
  - Ensure these details are stored and managed in a Supabase Postgres table "users"
  - Make the provided static code dynamic to communicate with Supabase for updating profile details and storing profile pictures

## Notes

- `DashboardSidebar` is a client component, while `UserDropdown` is a server component. Efforts have been made to convert `UserDropdown` to a client component using `utils/supabase/client#createClient()`, but issues persist.
- Ensure that the client component functions properly when integrated into the server component without causing bugs.
- Review the [Supabase guide](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?queryGroups=language&language=ts#bonus-profile-photos) for handling profile pictures.
- Profile details should link to the user ID in the Supabase Postgres table "users" to show internal Supabase info if needed.

**Comment by jjfantini** [comment]
Here is an example dashboard to showcase UserDropdown functionality:

https://nextui-dashboard-template.vercel.app
