### ISSUE TITLE
[FEAT]: `profile-settings` page changes

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#54]
# Main Goal
The feature to upload profile images had ben added last week, but in a buggy branch. It needs to be done. I expect this to be done quickly since the logic in the stack has already been thought about with the last implementation. You will also be adding small changes to account editing fields.

# Tasks
- [x] add ability to upload when clicking blue edit pen (shown in picture below)
- [x] update the avatar picture in the top right hand corner
- [x] add pictures to bucket `profile_avatars`
- [x] grey out email and password change if the user used OAuth to sign in, only allow change if they use email/pass (can use user.metadata.providers) info too check (or a solution you use)
- [x] add the fields you had previously added
- [x] Allow editing of the following user details:
- Display name
- Email (greyed out if using OAuth)
- Password (greyed out if using OAuth)
- Accent color (tie to class that can be used for small colors around the dashboard)
- Default theme (dark or light)
- OpenBB Personal Access Token (under "Financial Services" section)
- InteractiveBroker API Key (under "Financial Services" section)

Save these values to `public.profiles` table.

![Image](https://github.com/user-attachments/assets/3658885c-78f7-458f-914c-40c2377f8ec2)

# Notes
THis picture should be able to be uploaded, notify user maximum upload is 15mb

# References:
[Supabase Guide](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?queryGroups=language&language=ts#bonus-profile-photos)

**Comment by jjfantini** [comment]
closed with #74
