### ISSUE TITLE
[FEAT]: Assign `membership` value when user signs up with Stripe

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#58]
# Main Goal
When a user signs up for a stripe membership, insert the value (peon, premium, power, permanent) into `public.profiles.membership` column. This will be used for validating user roles to give access to certain functions/features

# Tasks
- [x] scrape the membership that the customer subscribed to
- [x] INSERT `membership` value to the users `public.profiles` row
- [x] This should update if the user changes subscription
- [x] Test that a purchase of a stripe subscription assigns all types of membership, and ensure that a mmebrship upgrade also UPDATES their `membership` role in the `public.profiles` table.

**Comment by jjfantini** [comment]
Logic added in #69

**Comment by jjfantini** [comment]
closed with #73
