### ISSUE TITLE
[FEAT]: Setup `dashboard/home`

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#60]
# Main Goal
This is to make the home page of the dashboard more user-firendly and show important information to the user. There are going to be charts and tables on this page, that need to be organized to be viewable on a mobile device. There are going to be 3 charts. One tradingview widget, one subset and set list of symbols showing `user-table` data, one plotly object showing a price chart (API endpoint tbc)

# Tasks
- [x] Add TradingView [Widget](https://www.tradingview.com/widget-docs/widgets/charts/symbol-overview/) for SPX
- [x] Include [Ticker Tape](https://www.tradingview.com/widget-docs/widgets/tickers/ticker-tape/) at the top
- [x] Add table with smaller subset (only `symbol, recent_price, buy_price. sell_price` columns) of `user-table` data for these symbols: `UST, SPX, RUT, NASDAQ, XLK, XLE, XLRE, XLU, XLF, XLP, XLC, XLY, XLV, XLI, XLB, VIX, USD, WTI`
- [ ] Add Plotly Chart from `/mandelbrot-channel?chart=True` API endpoint for SPX.

# Notes
I will provide the API endpoint to access and give you the parameters to pass.
