### ISSUE TITLE
[FEAT]: `UserTable` Functionality Update

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#61]
# Main Goal
We need to allow users to select a default watchlist to always load first upon arriving to the `Portfolio` tab. In the dropdown to select a watchlist, there should be a Button to `Set Default`, which will update a field in `public.profiles.default_watchlist` to the watchlist in which the button was pressed. This will now mark the Watchlist `Set to Default ✓` in greyed-out text. There also needs to be caching with `lru-cache` so that the data initially fetched (once per day for everyone) stays on the webpage and doesn't revalidate the API call every time the user navigates to the `Portfolio` tab. Along with this, we need to add a `Refresh Data` (with a circular icon) button that is the only way to revalidate the API call and get new data, bypassing the cache. This will be a feature that is only available multiple times for some users (described below). 

# Tasks
- [x] Add `UserTable` data caching
    - [x] cache the data after running the inital cron job/first data fetch. Re-fetch the data if the refresh button is clicked, or if it is a new day and the data is from yesterday.
- [x] Add `UserTable` default watchlist option
    - [x] add a button to the dropdown options of watchlists, this button should be green and say `Set Default`
    - [x] once clicked, set `public.profiles.default_watchlist` to the selected watchlist and then set faint grey text  `Set to Default ✓`
    - [ ] this defualt watchlist should have its data preloaded when the user enters the website, so the dont need to wait for it to load when going to `Portfolio` page, you can use [Vercel Cron Jobs](https://vercel.com/humblhumans/humblfinance-frontend/settings/cron-jobs) for this? You can hit the API endpoints and load that data for the user
- [x] Add a `Refresh Data` button above the table
    - [x] this button should re-fetch the data form the API for the watchlist they are viewing
    - [x] this button should be restricted to its usage:
         - [x] anonymous users: 0 refreshed
         - [x] peon: 1 refresh
         - [x] premium: 3 refreshes
         - [x] power: 5 refreshes
         - [x] permanent: unlimited
         - [x] admin: unlimited
-[ ] Add toast notifications for succesful refreshes, changed watchlist default, and errors if they occur

# References 
Check Discord Issue Thread for video
