### ISSUE TITLE
[BUG]: Update `Watchlist` functionality

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblFINANCE-frontend#63]
# Main Goal
I have changed the column names of the tables in the DB, and I have updated the references to them in the code @cundus has made. It seems that when a user enters a new watchlist, it gets created (I can see it on the dashboard) but it does not show in the `WatchlistModal`. This needs to be fixed and returned to its working state. This houl sbe easy becuase I just need @cundus to go through the name changes and cinrim the logic he had to originally accomplish this. 

I prefer symbols name over ticker/stock, so please use that where applicable. 

# Tasks
- [x] Validate tickers against `public.all_symbols` table when entered in a watchlist
- [x] Make sure User watchlists are able to be CRUD and show in dropdown and `WatchlstModal`
- [x] Fire `UpgradeUserModal` when the user has reached their max limit of watchlists
- [x] Add 10 options to the ticker selection
- [x] Add ability to select Default Watchlist

humblPEON: Can create 2 watchlist.
humblPREMIUM: Can create up to 5 watchlists.
humblPOWER: can create 10 watchlists
humblPERMANENT: Can create unlimited watchlists.

You need to complete #58 bfore doing this, so the `public.profiles.membership` value is accessible.

**Comment by jjfantini** [comment]
@cundus see the 2 new tasks I have added that we discussed in discord.
 
I am going to merge #73 and you can complete the next 2 tasks in a new branch :)
